AWSTemplateFormatVersion: 2010-09-09
Description: Create an IAM role for configuration in the delegated administrator account

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Role Attributes
        Parameters:
          - pConfigurationRoleName
          - pOrgPrimaryLambdaRoleName
          - pOrgPrimaryAccountId
          - pTagKey1
          - pTagValue1

    ParameterLabels:
      pConfigurationRoleName:
        default: Configuration IAM Role Name
      pOrgPrimaryLambdaRoleName:
        default: Organization Primary Lambda Role Name
      pOrgPrimaryAccountId:
        default: Organization Primary Account ID
      pTagKey1:
        default: Lambda Role Tag Key
      pTagValue1:
        default: Lambda Role Tag Value

Parameters:
  pOrgPrimaryAccountId:
    Type: String
    Description: Organization Primary Account ID

  pConfigurationRoleName:
    Type: String
    Description: Configuration IAM Role Name

  pOrgPrimaryLambdaRoleName:
    Type: String
    Description: Organization Primary Account Lambda Role Name

  pTagKey1:
    Type: String
    Description: Tag key

  pTagValue1:
    Type: String
    Description: Tag key value

Resources:
  rConfigurationRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Actions require * in resource
          - id: W28
            reason: Explicit name provided for automation resource identification
    Properties:
      RoleName: !Ref pConfigurationRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pOrgPrimaryAccountId}:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:PrincipalArn: !Sub arn:${AWS::Partition}:iam::${pOrgPrimaryAccountId}:role/${pOrgPrimaryLambdaRoleName}
      Path: "/"
      Policies:
        - PolicyName: "guardduty-org-policy-organizations"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: Organizations
                Effect: Allow
                Action: organizations:ListAccounts
                Resource: "*"

        - PolicyName: "guardduty-org-policy-guardduty"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: GuardDutyNoResource
                Effect: Allow
                Action: guardduty:ListDetectors
                Resource: "*"

              - Sid: GuardDutyWithResource
                Effect: Allow
                Action:
                  - guardduty:CreateMembers
                  - guardduty:CreatePublishingDestination
                  - guardduty:DeleteDetector
                  - guardduty:DeleteMembers
                  - guardduty:DisassociateMembers
                  - guardduty:ListMembers
                  - guardduty:ListPublishingDestinations
                  - guardduty:UpdateDetector
                  - guardduty:UpdateOrganizationConfiguration
                  - guardduty:UpdatePublishingDestination
                Resource:
                  - !Sub arn:${AWS::Partition}:guardduty:*:${AWS::AccountId}:/detector/*
                  - !Sub arn:${AWS::Partition}:guardduty:*:${AWS::AccountId}:detector/*

        - PolicyName: "guardduty-org-policy-iam"
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Sid: AllowReadIamActions
                Effect: Allow
                Action: iam:GetRole
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*

              - Sid: AllowCreateDeleteServiceLinkedRole
                Effect: Allow
                Action:
                  - iam:CreateServiceLinkedRole
                  - iam:DeleteServiceLinkedRole
                Resource:
                  - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/aws-service-role/guardduty.amazonaws.com/AWSServiceRoleForAmazonGuardDuty
                Condition:
                  StringLike:
                    iam:AWSServiceName: guardduty.amazonaws.com

              - Sid: AllowPolicyActions
                Effect: Allow
                Action:
                  - iam:PutRolePolicy
                  - iam:DeleteRolePolicy
                Resource:
                  - !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/aws-service-role/guardduty.amazonaws.com/AWSServiceRoleForAmazonGuardDuty
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1
