########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the GuardDuty Delivery KMS Key

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: KMS Key Attributes
        Parameters:
          - pGuardDutyDeliveryKeyAlias
          - pOrgManagementAccountId
          - pLoggingAccountId
          - pTagKey1
          - pTagValue1

    ParameterLabels:
      pGuardDutyDeliveryKeyAlias:
        default: GuardDuty Delivery KMS Key Alias
      pOrgManagementAccountId:
        default: Organization Management Account ID
      pLoggingAccountId:
        default: Security Log Archive Account ID
      pTagKey1:
        default: Tag Key
      pTagValue1:
        default: Tag Value

Parameters:
  pGuardDutyDeliveryKeyAlias:
    Type: String
    Description: GuardDuty Delivery KMS Key Alias
    Default: GuardDutyDeliveryKMSKey

  pOrgManagementAccountId:
    Type: String
    Description: Organization management account ID

  pLoggingAccountId:
    Type: String
    Description: Organization log archive account ID

  pTagKey1:
    Type: String
    Description: Tag key

  pTagValue1:
    Type: String
    Description: Tag key value

Resources:
  rGuardDutyDeliveryKey:
    Type: AWS::KMS::Key
    Properties:
      Description: GuardDuty Delivery Key
      EnableKeyRotation: True
      KeyPolicy:
        Version: '2012-10-17'
        Id: !Sub ${pGuardDutyDeliveryKeyAlias}
        Statement:
          - Sid: Enable IAM User Permissions
            Effect: Allow
            Action: 'kms:*'
            Resource: '*'
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root

          - Action: kms:GenerateDataKey
            Effect: Allow
            Principal:
              Service: guardduty.amazonaws.com
            Resource: '*'
            Sid: Allow GuardDuty to encrypt logs

          - Sid: Allow alias creation during setup
            Effect: Allow
            Action: kms:CreateAlias
            Condition:
              StringEquals:
                'kms:CallerAccount': !Sub ${AWS::AccountId}
                'kms:ViaService': cloudformation.us-east-1.amazonaws.com
            Resource: '*'
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root

          - Sid: Allow Log Archive and Management account access
            Effect: Allow
            Action: kms:Decrypt
            Resource: '*'
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pLoggingAccountId}:root
                - !Sub arn:${AWS::Partition}:iam::${pOrgManagementAccountId}:root

          - Sid: Allow account access
            Effect: Allow
            Action:
              - kms:DescribeKey
              - kms:Decrypt
            Resource: '*'
            Principal:
              AWS: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:root

      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1

  rGuardDutyDeliveryKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${pGuardDutyDeliveryKeyAlias}
      TargetKeyId: !Ref rGuardDutyDeliveryKey

Outputs:
  oGuardDutyDeliveryKeyArn:
    Description: GuardDuty Delivery KMS Key ARN
    Value: !GetAtt rGuardDutyDeliveryKey.Arn
