########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: '2010-09-09'
Description: Account Password Policy

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Password Policy Parameters
        Parameters:
        - pAllowUsersToChangePassword
        - pHardExpiry
        - pMaxPasswordAge
        - pMinimumPasswordLength
        - pPasswordReusePrevention
        - pRequireLowercaseCharacters
        - pRequireNumbers
        - pRequireSymbols
        - pRequireUppercaseCharacters

      - Label:
          default: Lambda Parameters
        Parameters:
          - pLambdaExecutionRoleName
          - pLambdaFunctionName
          - pLambdaS3BucketName
          - pLambdaZipFileName
          - pLogLevel

    ParameterLabels:
      pAllowUsersToChangePassword:
        default: Allow Users to Change Password
      pHardExpiry:
        default: Hard Expiry
      pMaxPasswordAge:
        default: Max Password Age
      pMinimumPasswordLength:
        default: Minimum Password Length
      pPasswordReusePrevention:
        default: Password Reuse Prevention
      pRequireLowercaseCharacters:
        default: Require Lowercase Characters
      pRequireNumbers:
        default: Require Numbers
      pRequireSymbols:
        default: Require Symbols
      pRequireUppercaseCharacters:
        default: Require Uppercase Characters

      pLambdaExecutionRoleName:
        default: Lambda Execution Role Name
      pLambdaFunctionName:
        default: Lambda Function Name
      pLambdaS3BucketName:
        default: Lambda S3 Bucket Name
      pLambdaZipFileName:
        default: Lambda Zip File Name
      pLogLevel:
        default: Log Level

Parameters:
  pAllowUsersToChangePassword:
    AllowedValues: [true, false]
    Default: true
    Description: 'You can permit all IAM users in your account to use the IAM console to change their own passwords.'
    Type: String

  pHardExpiry:
    AllowedValues: [true, false]
    Default: false
    Description: 'You can prevent IAM users from choosing a new password after their current password has expired.'
    Type: String

  pLambdaExecutionRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Description: Lambda execution role name
    Default: password-policy-acct
    Type: String

  pLambdaFunctionName:
    AllowedPattern: '^[\w-]{0,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [_, -]
    Description: Lambda function name
    Type: String

  pLambdaS3BucketName:
    AllowedPattern: "^$|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription:
      S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Description:
      The Amazon S3 bucket name where the lambda zip file is stored. Example Bucket Name = lambda-zips-us-east-1
    Type: String

  pLambdaZipFileName:
    Description: Lambda zip file name containing code
    Type: String

  pLogLevel:
    AllowedValues: [ debug, info, warning, error, critical ]
    Default: debug
    Description: Lambda Function Logging Level
    Type: String

  pMaxPasswordAge:
    ConstraintDescription: 'Must be in the range [0-1095]'
    Default: 90
    Description: 'You can set IAM user passwords to be valid for only the specified number of days.'
    MaxValue: 1095
    MinValue: 0
    Type: Number

  pMinimumPasswordLength:
    ConstraintDescription: 'Must be in the range [6-128]'
    Default: 14
    Description: 'You can specify the minimum number of characters allowed in an IAM user password.'
    MaxValue: 128
    MinValue: 6
    Type: Number

  pPasswordReusePrevention:
    ConstraintDescription: 'Must be in the range [0-24]'
    Default: 24
    Description: 'You can prevent IAM users from reusing a specified number of previous passwords.'
    MaxValue: 24
    MinValue: 0
    Type: Number

  pRequireLowercaseCharacters:
    AllowedValues: [true, false]
    Default: true
    Description: 'You can require that IAM user passwords contain at least one lowercase character from the ISO basic Latin alphabet (a to z).'
    Type: String

  pRequireNumbers:
    AllowedValues: [true, false]
    Default: true
    Description: 'You can require that IAM user passwords contain at least one numeric character (0 to 9).'
    Type: String

  pRequireSymbols:
    AllowedValues: [true, false]
    Default: true
    Description: 'You can require that IAM user passwords contain at least one of the following nonalphanumeric characters: ! @ # $ % ^ & * ( ) _ + - = [ ] {} | '''
    Type: String

  pRequireUppercaseCharacters:
    AllowedValues: [true, false]
    Default: true
    Description: 'You can require that IAM user passwords contain at least one uppercase character from the ISO basic Latin alphabet (A to Z).'
    Type: String

Resources:
  rLambdaRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Allow Resource * for IAM APIs. The password policy does not have the ARN namespace.
          - id: W28
            reason: The role name is defined
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: lambda.amazonaws.com

      Path: '/'
      Policies:
        - PolicyDocument:
            Statement:
              - Action: logs:CreateLogGroup
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${pLambdaFunctionName}:*
                Sid: CreateLogGroup

              - Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${pLambdaFunctionName}:log-stream:*
                Sid: CreateLogStreamAndEvents

              - Action: iam:UpdateAccountPasswordPolicy
                Effect: Allow
                Resource: '*'
                Sid: IAMUpdateAccountPasswordPolicy
            Version: 2012-10-17
          PolicyName: update-iam-password-policy
      RoleName: !Ref pLambdaExecutionRoleName

  rLambdaFunction:
    Type: AWS::Lambda::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W58
            reason: CloudWatch access provided by the attached IAM role
          - id: W89
            reason: Lambda is not deployed inside a VPC
    Properties:
      Code:
        S3Bucket: !Ref pLambdaS3BucketName
        S3Key: !Ref pLambdaZipFileName
      Description: Update IAM password policy
      Environment:
        Variables:
          LOG_LEVEL: !Ref pLogLevel
      Handler: app.lambda_handler
      MemorySize: 128
      ReservedConcurrentExecutions: 1
      Role: !GetAtt rLambdaRole.Arn
      Runtime: 'python3.9'
      Timeout: 60

  rPasswordPolicy:
    Type: Custom::PasswordPolicy
    Version: '1.0'
    Properties:
      AllowUsersToChangePassword: !Ref pAllowUsersToChangePassword
      HardExpiry: !Ref pHardExpiry
      MaxPasswordAge: !Ref pMaxPasswordAge
      MinimumPasswordLength: !Ref pMinimumPasswordLength
      PasswordReusePrevention: !Ref pPasswordReusePrevention
      RequireLowercaseCharacters: !Ref pRequireLowercaseCharacters
      RequireNumbers: !Ref pRequireNumbers
      RequireSymbols: !Ref pRequireSymbols
      RequireUppercaseCharacters: !Ref pRequireUppercaseCharacters
      ServiceToken: !GetAtt rLambdaFunction.Arn
