########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description: Create an IAM role to disassociate the administrator account

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label: 
          default: Role Attributes
        Parameters:
          - pFMSDisassociateRoleName
          - pOrgManagementAccountId
          - pOrgManagementLambdaRoleName
          - pTagKey1
          - pTagValue1

    ParameterLabels:
      pFMSDisassociateRoleName:
        default: FMS Disassociate IAM Role Name
      pOrgManagementAccountId:
        default: Organization Management Account ID
      pOrgManagementLambdaRoleName: 
        default: Organization Management Lambda Role Name
      pTagKey1: 
        default: Lambda Role Tag Key
      pTagValue1: 
        default: Lambda Role Tag Value
      
Parameters:
  pFMSDisassociateRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Description: FMS IAM Role Name
    Type: String

  pOrgManagementAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Organization management account ID
    Type: String

  pOrgManagementLambdaRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Description: Organization Management Account Lambda Role Name
    Type: String

  pTagKey1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters and cannot be prefixed with "aws:".
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-''
    Description: Tag key
    Type: String

  pTagValue1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters.
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-'
    Description: Tag key value
    Type: String

Resources:
  rFMSDisassociateRole: 
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Allow put and delete configuration aggregator for all aggregators
          - id: W28
            reason: Explicit name provided for automation resource identification
    Properties:
      RoleName: !Ref pFMSDisassociateRoleName
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:PrincipalArn:
                  - !Sub arn:${AWS::Partition}:iam::${pOrgManagementAccountId}:role/${pOrgManagementLambdaRoleName}
            Effect: "Allow"
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pOrgManagementAccountId}:root

      Path: "/"
      Policies: 
        - PolicyName: !Ref pFMSDisassociateRoleName
          PolicyDocument:
            Version: 2012-10-17
            Statement:         
              - Action:
                  - fms:DisassociateAdminAccount
                  - fms:GetAdminAccount
                Effect: Allow
                Resource: "*"
                Sid: AllowFMSDisassociateAdminAccount

              - Action:
                  - organizations:DescribeAccount
                  - organizations:DescribeOrganization
                  - organizations:ListAccounts
                Effect: Allow
                Resource: "*"
                Sid: OrganizationAccess
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1
