AWSTemplateFormatVersion: 2010-09-09
Description: Create an IAM role for configuration in the delegated administrator account

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Role Attributes
        Parameters:
          - pConfigurationRoleName
          - pOrgManagementAccountId
          - pLambdaRoleName
          - pTagKey1
          - pTagValue1

    ParameterLabels:
      pConfigurationRoleName:
        default: Configuration IAM Role Name
      pOrgManagementAccountId:
        default: Organization Management Account ID
      pLambdaRoleName:
        default: Lambda Role Name
      pTagKey1:
        default: Lambda Role Tag Key
      pTagValue1:
        default: Lambda Role Tag Value

Parameters:
  pConfigurationRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Description: Configuration IAM Role Name
    Type: String

  pOrgManagementAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Organization Management Account ID
    Type: String

  pLambdaRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Description: Lambda Role Name
    Type: String

  pTagKey1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters and cannot be prefixed with "aws:".
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-''
    Description: Tag key
    Type: String

  pTagValue1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters.
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-'
    Description: Tag key value
    Type: String

Resources:
  rConfigurationRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: Actions require * in resource
          - id: W28
            reason: Explicit name provided
    Properties:
      RoleName: !Ref pConfigurationRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:PrincipalArn: !Sub arn:${AWS::Partition}:iam::${pOrgManagementAccountId}:role/${pLambdaRoleName}
            Effect: "Allow"
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pOrgManagementAccountId}:root

      Path: "/"
      Policies:
        - PolicyName: macie-org-policy-organizations
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: organizations:ListAccounts
                Effect: Allow
                Resource: "*"
                Sid: Organizations

        - PolicyName: macie-org-policy-macie
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - macie2:DescribeBuckets
                  - macie2:DescribeOrganizationConfiguration
                  - macie2:DisableMacie
                  - macie2:DisableOrganizationAdminAccount
                  - macie2:DisassociateFromMasterAccount
                  - macie2:EnableMacie
                  - macie2:EnableOrganizationAdminAccount
                  - macie2:GetClassificationExportConfiguration
                  - macie2:GetMasterAccount
                  - macie2:ListMembers
                  - macie2:ListOrganizationAdminAccounts
                  - macie2:PutClassificationExportConfiguration
                  - macie2:UpdateMacieSession
                  - macie2:UpdateOrganizationConfiguration
                Effect: Allow
                Resource: "*"
                Sid: MacieNoResource

              - Action:
                  - macie2:CreateMember
                  - macie2:DeleteMember
                  - macie2:DisassociateMember
                  - macie2:GetMember
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:macie2:*:${AWS::AccountId}:*
                Sid: MacieMember

        - PolicyName: macie-org-policy-iam
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: iam:GetRole
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/*
                Sid: AllowReadIamActions

              - Action:
                  - iam:CreateServiceLinkedRole
                  - iam:DeleteServiceLinkedRole
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/aws-service-role/macie.amazonaws.com/AWSServiceRoleForAmazonMacie
                Sid: AllowCreateDeleteServiceLinkedRole

              - Action:
                  - iam:DeleteRolePolicy
                  - iam:PutRolePolicy
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:iam::${AWS::AccountId}:role/aws-service-role/macie.amazonaws.com/AWSServiceRoleForAmazonMacie
                Sid: AllowPolicyActions

      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1
