---
#Default region for deploying Custom Control Tower: Code Pipeline, Step functions, Lambda, SSM parameters, and StackSets
region: us-east-1
version: 2021-03-15

# Control Tower Custom Resources (Service Control Policies or CloudFormation)
resources:
# -----------------------------------------------------------------------------
# Organization Config Conformance Pack
# -----------------------------------------------------------------------------
  - name: ConformancePackDelegatedAdmin
    resource_file: templates/conformance-pack-org-register-delegated-admin.yaml
    parameters:
      - parameter_key: pDefaultLogGroupRetention
        parameter_value: "30"
      - parameter_key: pDelegatedAdminAccountId
        parameter_value: $[alfred_ssm_/org/member/Audit/account_id]
      - parameter_key: pLambdaExecutionRoleName
        parameter_value: cfct-config-register-delegated-admin-lambda
      - parameter_key: pLambdaFunctionName
        parameter_value: cfct-config-register-delegated-admin
      - parameter_key: pLambdaS3BucketName
        parameter_value: $[alfred_ssm_/org/primary/lambda_zips_bucket/us-east-1]
      - parameter_key: pLambdaZipFileName
        parameter_value: organization-register-delegated-admin.zip
      - parameter_key: pLogLevel
        parameter_value: info
      - parameter_key: pTagKey1
        parameter_value: cfct
      - parameter_key: pTagValue1
        parameter_value: managed-by-cfct
    deploy_method: stack_set
    deployment_targets:
      accounts:
        - Control Tower Management

  - name: ConformancePackDeliveryBucket
    resource_file: templates/conformance-pack-org-delivery-bucket.yaml
    parameters:
      - parameter_key: pOrganizationId
        parameter_value: $[alfred_ssm_/org/primary/organization_id]
      - parameter_key: pTagKey1
        parameter_value: cfct
      - parameter_key: pTagValue1
        parameter_value: managed-by-cfct
    deploy_method: stack_set
    deployment_targets:
      accounts:
        - Log archive
    export_outputs:
      - name: /org/config/conformance_pack_delivery_bucket
        value: $[output_oConformancePackDeliveryBucket]

  - name: ConformancePackDeployment
    resource_file: templates/conformance-pack-org-deployment.yaml
    parameters:
      - parameter_key: pConformancePackName
        parameter_value: Operational-Best-Practices-for-Encryption-and-Keys
      - parameter_key: pDeliveryBucketName
        parameter_value: $[alfred_ssm_/org/config/conformance_pack_delivery_bucket]
      - parameter_key: pDeliveryS3KeyPrefix
        parameter_value: Config
      - parameter_key: pExcludedAccounts
        parameter_value: $[alfred_ssm_/org/member/Control-Tower-Management/account_id]
      - parameter_key: pTemplateBucketName
        parameter_value: $[alfred_ssm_/org/config/conformance_pack_templates_bucket]
      - parameter_key: pTemplatePrefix
        parameter_value: Operational-Best-Practices-for-Encryption-and-Keys.yaml
    deploy_method: stack_set
    deployment_targets:
      accounts:
        - Audit
    regions:
      - ap-southeast-2
      - eu-west-1
      - us-east-1
      - us-east-2
      - us-west-2
