########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description: Register delegated administrator account

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Lambda Function Attributes
        Parameters:
          - pDelegatedAdminAccountId
          - pLambdaFunctionName
          - pLambdaS3BucketName
          - pLambdaZipFileName
          - pLogLevel
          - pServicePrincipalList
      - Label:
          default: Lambda Role Attributes
        Parameters:
          - pLambdaExecutionRoleName
          - pTagKey1
          - pTagValue1

    ParameterLabels:
      pDelegatedAdminAccountId:
        default: Delegated Admin Account ID
      pLambdaExecutionRoleName:
        default: Lambda Role Name
      pLambdaFunctionName:
        default: Lambda Function Name
      pLambdaS3BucketName:
        default: Lambda Source S3 Bucket Name
      pLambdaZipFileName:
        default: Lambda Zip File Name
      pLogLevel:
        default: Lambda Function Log Level
      pServicePrincipalList:
        default: Service Principal List
      pTagKey1:
        default: Tag Key
      pTagValue1:
        default: Tag Value

Parameters:
  pDelegatedAdminAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Delegated administrator account ID
    Type: String

  pLambdaExecutionRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: register-delegated-admin-lambda
    Type: String

  pLambdaFunctionName:
    AllowedPattern: '^[\w-]{0,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [_, -]
    Default: register-delegated-admin
    Description: Lambda function name
    Type: String

  pLambdaS3BucketName:
    AllowedPattern: '^$|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$'
    ConstraintDescription:
      S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen (-).
    Description: The Amazon S3 bucket name where the lambda zip file is stored
    Type: String

  pLambdaZipFileName:
    Default: common-register-delegated-administrator.zip
    Description: Lambda zip file containing code
    Type: String

  pLogLevel:
    AllowedValues: [debug, info, warning, error, critical]
    Default: info
    Description: Lambda Function Logging Level
    Type: String

  pServicePrincipalList:
    #    AllowedValues:
    #      - access-analyzer.amazonaws.com
    #      - auditmanager.amazonaws.com
    #      - config-multiaccountsetup.amazonaws.com
    #      - config.amazonaws.com
    #      - macie.amazonaws.com
    #      - securityhub.amazonaws.com
    #      - stacksets.cloudformation.amazonaws.com
    #      - storage-lens.s3.amazonaws.com
    Description: Comma delimited list of AWS service principals to delegate an administrator account
    Type: CommaDelimitedList

  pTagKey1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters and cannot be prefixed with "aws:". The string can contain only the set of Unicode letters, digits,
      white-space, '_', '.', '/', '=', '+', '-''
    Description: Tag key
    Type: String

  pTagValue1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters. The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=',
      '+', '-'
    Description: Tag key value
    Type: String

Resources:
  rLambdaRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: The organizations actions do not allow resource restrictions
          - id: W28
            reason: The role name is defined to identify resources
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: '/'
      Policies:
        - PolicyName: register-delegated-admin-policy-logs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: logs:CreateLogGroup
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${pLambdaFunctionName}:log-stream:*
                Sid: CreateLogGroup

              - Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${pLambdaFunctionName}:log-stream:*
                Sid: CreateLogStreamAndEvents

        - PolicyName: register-delegated-admin-policy-organizations
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - organizations:DeregisterDelegatedAdministrator
                  - organizations:DescribeOrganization
                  - organizations:DisableAWSServiceAccess
                  - organizations:EnableAWSServiceAccess
                  - organizations:ListAWSServiceAccessForOrganization
                  - organizations:ListDelegatedAdministrators
                  - organizations:RegisterDelegatedAdministrator
                Effect: Allow
                Resource: '*'
                Sid: OrganizationsAccess
      RoleName: !Ref pLambdaExecutionRoleName
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1

  rLambdaFunction:
    Type: AWS::Lambda::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W58
            reason: CloudWatch access provided by the attached IAM role
          - id: W89
            reason: Lambda is not deployed within a VPC
    Properties:
      Code:
        S3Bucket: !Ref pLambdaS3BucketName
        S3Key: !Ref pLambdaZipFileName
      Description: Register AWS Config delegated admin account
      Environment:
        Variables:
          LOG_LEVEL: !Ref pLogLevel
      FunctionName: !Ref pLambdaFunctionName
      Handler: app.lambda_handler
      MemorySize: 128
      ReservedConcurrentExecutions: 1
      Role: !GetAtt rLambdaRole.Arn
      Runtime: python3.9
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1
      Timeout: 300

  rLambdaCustomResource:
    Type: Custom::LambdaCustomResource
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt rLambdaFunction.Arn
      AWS_SERVICE_PRINCIPAL_LIST: !Ref pServicePrincipalList
      DELEGATED_ADMIN_ACCOUNT_ID: !Ref pDelegatedAdminAccountId
