########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description: AWS Config register delegated administrator account

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label: 
          default: Lambda Function Attributes
        Parameters:
          - pDefaultLogGroupRetention
          - pDelegatedAdminAccountId
          - pLambdaFunctionName
          - pLambdaS3BucketName
          - pLambdaZipFileName
          - pLogLevel
      -
        Label:
          default: Lambda Role Attributes
        Parameters:
          - pLambdaExecutionRoleName
          - pTagKey1
          - pTagValue1

    ParameterLabels:
      pDefaultLogGroupRetention:
        default: Default Log Group Retention
      pLambdaFunctionName:
        default: Lambda Function Name
      pLambdaS3BucketName: 
        default: Lambda Source S3 Bucket Name
      pLambdaZipFileName: 
        default: Lambda Zip File Name
      pDelegatedAdminAccountId:
        default: AWS Config Delegated Admin Account ID
      pLogLevel: 
        default: Lambda Function Log Level
      
      pLambdaExecutionRoleName: 
        default: Lambda Role Name
      pTagKey1:
        default: Tag Key
      pTagValue1:
        default: Tag Value

Parameters:
  pDefaultLogGroupRetention:
    Type: String
    Default: 14
    Description: Specifies the number of days you want to retain log events in the CloudWatch Logs
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]

  pDelegatedAdminAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Delegated administrator account ID
    Type: String

  pLambdaFunctionName:
    AllowedPattern: '^[\w-]{0,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [_, -]
    Description: Lambda function name
    Type: String

  pLambdaExecutionRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: config-register-delegated-admin-lambda
    Type: String

  pLambdaS3BucketName:
    AllowedPattern: "^$|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription:
      S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Description: The Amazon S3 bucket name where the lambda zip file is stored
    Type: String

  pLambdaZipFileName:
    Description: Lambda zip file containing code
    Type: String

  pLogLevel:
    AllowedValues: [debug, info, warning, error, critical]
    Default: info
    Description: Lambda Function Logging Level
    Type: String

  pTagKey1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters and cannot be prefixed with "aws:".
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-''
    Description: Tag key
    Type: String

  pTagValue1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters.
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-'
    Description: Tag key value
    Type: String
  

Mappings:
  mAWSServicePrincipal:
    config:
      ServicePrincipal: config-multiaccountsetup.amazonaws.com


Resources: 
  rLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W84
            reason: KMS key not provided
    Properties:
      RetentionInDays: !Ref pDefaultLogGroupRetention
      LogGroupName: !Sub "/aws/lambda/${pLambdaFunctionName}"

  rLambdaRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: The organizations actions do not allow resource restrictions
          - id: W28
            reason: The role name is defined to identify resources
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: conformance-pack-org-policy-logs
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action: logs:CreateLogGroup
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${rLambdaLogGroup}
                Sid: CreateLogGroup

              - Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Effect: Allow
                Resource: !Sub arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:${rLambdaLogGroup}:log-stream:*
                Sid: CreateLogStreamAndEvents

        - PolicyName: conformance-pack-org-policy-organizations
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Action:
                  - organizations:DeregisterDelegatedAdministrator
                  - organizations:DescribeOrganization
                  - organizations:DisableAWSServiceAccess
                  - organizations:EnableAWSServiceAccess
                  - organizations:ListAWSServiceAccessForOrganization
                  - organizations:ListDelegatedAdministrators
                  - organizations:RegisterDelegatedAdministrator
                Effect: Allow
                Resource: "*"
                Sid: Organizations
      RoleName: !Ref pLambdaExecutionRoleName
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1

  rLambdaFunction:
    Type: AWS::Lambda::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W58
            reason: CloudWatch access provided by the attached IAM role
          - id: W89
            reason: Lambda is not deployed within a VPC
    Properties:
      Code:
        S3Bucket: !Ref pLambdaS3BucketName
        S3Key: !Ref pLambdaZipFileName
      Description: Update the S3 account level public access block settings
      Environment:
        Variables:
          LOG_LEVEL: !Ref pLogLevel
      FunctionName: !Ref pLambdaFunctionName
      Handler: app.lambda_handler
      MemorySize: 128
      ReservedConcurrentExecutions: 1
      Role: !GetAtt rLambdaRole.Arn
      Runtime: python3.8
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1
      Timeout: 300

  rLambdaCustomResource:
    Type: Custom::LambdaCustomResource
    Version: "1.0"
    Properties:
      ServiceToken: !GetAtt rLambdaFunction.Arn
      AWS_SERVICE_PRINCIPAL: !FindInMap [mAWSServicePrincipal, "config", "ServicePrincipal"]
      DELEGATED_ADMIN_ACCOUNT_ID: !Ref pDelegatedAdminAccountId