AWSTemplateFormatVersion: 2010-09-09
Description: AWS Config Organization Conformance Pack

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Conformance Pack Attributes
        Parameters:
          - pConformancePackName
          - pTemplateBucketName
          - pTemplatePrefix
          - pExcludedAccounts

      -
        Label:
          default: Delivery Bucket Attributes
        Parameters:
          - pDeliveryBucketName
          - pDeliveryS3KeyPrefix

    ParameterLabels:
      pConformancePackName:
        default: Conformance Pack Name
      pTemplateBucketName:
        default: Conformance Pack Template Bucket Name
      pTemplatePrefix:
        default: Conformance Pack Template File Name
      pExcludedAccounts:
        default: Account IDs to exclude from the conformance pack

      pDeliveryBucketName:
        default: Conformance pack delivery bucket name
      pDeliveryS3KeyPrefix:
        default: Conformance pack delivery bucket prefix

Parameters:
  pConformancePackName:
    Type: String
    Description: The name you assign to an organization conformance pack.

  pDeliveryBucketName:
    Type: String
    Description: >
      Location of an Amazon S3 bucket where AWS Config can deliver evaluation results and conformance pack
      template that is used to create a pack.

  pDeliveryS3KeyPrefix:
    Type: String
    Description: Path to deliver the conformance pack rules e.g. Config

  pTemplateBucketName:
    Type: String
    Description: Conformance pack template bucket name

  pTemplatePrefix:
    Type: String
    Description: Path and file name of the conformance pack template e.g. /conformance-packs/my-conformance-pack.yaml

  pExcludedAccounts:
    Type: String
    Description: Comma delimited list of account IDs to exclude from the conformance pack

Conditions:
  cExcludedAccounts: !Not [!Equals [!Ref pExcludedAccounts, '']]

Resources:
  rConformancePack:
    Type: AWS::Config::OrganizationConformancePack
    Properties:
      OrganizationConformancePackName: !Ref pConformancePackName
      DeliveryS3Bucket: !Ref pDeliveryBucketName
      DeliveryS3KeyPrefix: !Ref pDeliveryS3KeyPrefix
      TemplateS3Uri: !Sub s3://${pTemplateBucketName}/${pTemplatePrefix}
      ExcludedAccounts: !If [cExcludedAccounts, !Split [",", !Ref pExcludedAccounts], !Ref 'AWS::NoValue']
