AWSTemplateFormatVersion: '2010-09-09'
Description: Creates S3 buckets to store the conformance pack results

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - 
        Label: 
          default: Bucket Attributes
        Parameters:
          - pOrganizationId
          - pTagKey1
          - pTagValue1

    ParameterLabels:
      pOrganizationId:
        default: AWS Organizations ID
      pTagKey1: 
        default: Tag Key
      pTagValue1: 
        default: Tag Value

Parameters:
  pOrganizationId:
    Type: String
    Description: AWS Organizations ID
    MinLength: 12
    MaxLength: 12
    AllowedPattern: '^o-[a-z0-9]{10,32}$'
    ConstraintDescription: >
      The Org Id must be a 12 character string starting with o- and followed by 10 lower case alphanumeric characters

  pTagKey1:
    Type: String 
    Description: Tag key
  
  pTagValue1:
    Type: String 
    Description: Tag key value


Resources:
  rConformancePackBucket:
    Type: AWS::S3::Bucket
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W35
            reason: "S3 access logging covered by CloudTrail S3 data events"
    DeletionPolicy: Retain
    Properties:
      BucketName: !Sub awsconfigconforms-${AWS::AccountId}-${AWS::Region}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1

  rConformancePackBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F16
            reason: "Allow * in resource for objects with aws:PrincipalOrgID condition"
    Properties:
      Bucket: !Ref rConformancePackBucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          
          - Sid: AWSConfigConformsBucketPermissionsCheck
            Effect: Allow
            Principal: "*"
            Action: s3:GetBucketAcl
            Resource: !Sub arn:${AWS::Partition}:s3:::${rConformancePackBucket}
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref pOrganizationId

          - Sid: AWSConfigConformsBucketDelivery
            Effect: Allow
            Principal: "*"
            Action: 
              - s3:PutObject
              - s3:PutObjectAcl 
            Resource: !Sub arn:${AWS::Partition}:s3:::${rConformancePackBucket}/*
            Condition:
              StringEquals:
                s3:x-amz-acl: bucket-owner-full-control
                aws:PrincipalOrgID: !Ref pOrganizationId

          - Sid: AWSConfigConformsBucketReadAccess
            Effect: Allow
            Principal: "*"
            Action: 
              - s3:GetObject
              - s3:GetObjectAcl
            Resource: !Sub arn:${AWS::Partition}:s3:::${rConformancePackBucket}/*
            Condition:
              StringEquals:
                aws:PrincipalOrgID: !Ref pOrganizationId

          - Sid: DenyExternalPrincipals
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource: 
              - !Sub arn:${AWS::Partition}:s3:::${rConformancePackBucket}
              - !Sub arn:${AWS::Partition}:s3:::${rConformancePackBucket}/*
            Condition:
              StringNotEquals:
                aws:PrincipalOrgID: !Ref pOrganizationId

          - Sid: SecureTransport
            Effect: Deny
            Principal: "*"
            Action: "s3:*"
            Resource:
              - !Sub arn:${AWS::Partition}:s3:::${rConformancePackBucket}
              - !Sub arn:${AWS::Partition}:s3:::${rConformancePackBucket}/*
            Condition:
              Bool:
                "aws:SecureTransport": "false"


Outputs:
  oConformancePackDeliveryBucket:
    Description: Conformance Pack Delivery Bucket
    Value: !Ref rConformancePackBucket