---
#Default region for deploying Custom Control Tower: Code Pipeline, Step functions, Lambda, SSM parameters, and StackSets
region: us-east-1
version: 2020-01-01

# Control Tower Custom Service Control Policies
organization_policies: []

# Control Tower Custom CloudFormation Resources
cloudformation_resources:
  # -----------------------------------------------------------------------------
  # AWS Config Aggregator Organization Solution
  # -----------------------------------------------------------------------------
  - name: AggregatorConfiguration
    template_file: templates/aggregator-org-configuration.yaml
    parameter_file: parameters/aggregator-org-configuration.json
    deploy_method: stack_set
    deploy_to_account:
      - Audit
