---
##############################################################################################################
# *** Make sure the core accounts in the manifest.yaml are listed top to bottom in the deployment order.
# Required Deployment Order:
# 1. primary
# 2. logging
# 3. security
##############################################################################################################
organizational_units: 
  - name: master  # Default configuration = core
    core_accounts:
      - name: primary
        core_resources:
          - name: ConformancePackDelegatedAdmin
            template_file: templates/conformance-pack-org-register-delegated-admin.yaml
            parameter_file: parameters/conformance-pack-org-register-delegated-admin.json
            deploy_method: stack_set

  - name: security:prod  # Default configuration = core
    core_accounts:
      - name: security
        core_resources:
          - name: ConformancePackDeployment
            template_file: templates/conformance-pack-org-deployment.yaml
            parameter_file: parameters/conformance-pack-org-deployment.json
            deploy_method: stack_set
            regions:
              - us-east-1
              - us-east-2
              # - ap-east-1
              - ap-northeast-1
              - ap-northeast-2
              - ap-south-1
              - ap-southeast-1
              - ap-southeast-2
              - ca-central-1
              - eu-central-1
              # - eu-north-1
              - eu-west-1
              - eu-west-2
              - eu-west-3
              # - me-south-1
              - sa-east-1
              - us-west-1
              - us-west-2
  
      - name: log-archive
        core_resources:
          - name: ConformancePackDeliveryBucket
            template_file: templates/conformance-pack-org-delivery-bucket.yaml
            parameter_file: parameters/conformance-pack-org-delivery-bucket.json
            deploy_method: stack_set
            ssm_parameters:
              - name: /org/config/conformance_pack_delivery_bucket
                value: $[output_oConformancePackDeliveryBucket]