########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description: AWS Control Tower Execution IAM Role Creation

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Control Tower Role Attributes
        Parameters:
          - pAWSControlTowerExecutionRoleName
          - pIAMTagKey
          - pIAMTagValue
          - pOrgPrimaryAccountId

    ParameterLabels:
      pAWSControlTowerExecutionRoleName:
        default: AWS Control Tower Execution Role Name
      pIAMTagKey:
        default: IAM Tag Key
      pIAMTagValue:
        default: IAM Tag Value
      pOrgPrimaryAccountId:
        default: AWS Organizations Primary Account ID

Parameters:
  pOrgPrimaryAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Organization primary account ID
    Type: String

  pAWSControlTowerExecutionRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: AWSControlTowerExecution
    Description: AWS Control Tower execution role name
    Type: String

  pIAMTagKey:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters and cannot be prefixed with "aws:".
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-''
    Default: cfct
    Description: IAM tag key
    Type: String

  pIAMTagValue:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters.
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-'
    Default: managed-by-cfct
    Description: IAM tag key value
    Type: String

Resources:
  rAWSControlTowerRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: Specific role name provided for AWS Control Tower
          - id: W43
            reason: Administrator policy is required for the role
    Properties:
      RoleName: !Ref pAWSControlTowerExecutionRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pOrgPrimaryAccountId}:root

      Path: "/"
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess
      Tags:
        - Key: !Ref pIAMTagKey
          Value: !Ref pIAMTagValue