########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: 2010-09-09
Description: AWS Config Organization Conformance Pack

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Conformance Pack Attributes
        Parameters:
          - pConformancePackName
          - pExcludedAccounts
          - pTemplateBucketName
          - pTemplatePrefix

      -
        Label:
          default: Delivery Bucket Attributes
        Parameters:
          - pDeliveryBucketName
          - pDeliveryS3KeyPrefix

    ParameterLabels:
      pConformancePackName:
        default: Conformance Pack Name
      pDeliveryBucketName:
        default: Conformance pack delivery bucket name
      pDeliveryS3KeyPrefix:
        default: Conformance pack delivery bucket prefix
      pExcludedAccounts:
        default: Account IDs to exclude from the conformance pack
      pTemplateBucketName:
        default: Conformance Pack Template Bucket Name
      pTemplatePrefix:
        default: Conformance Pack Template File Name

Parameters:
  pConformancePackName:
    Description: The name you assign to an organization conformance pack
    Type: String

  pDeliveryBucketName:
    AllowedPattern: "^$|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription:
      S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Description: >
      Location of an Amazon S3 bucket where AWS Config can deliver evaluation results and conformance pack
      template that is used to create a pack
    Type: String

  pDeliveryS3KeyPrefix:
    Description: Path to deliver the conformance pack rules e.g. Config
    Type: String

  pExcludedAccounts:
    Description: Comma delimited list of account IDs to exclude from the conformance pack
    Type: String

  pTemplateBucketName:
    AllowedPattern: "^$|^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$"
    ConstraintDescription:
      S3 bucket name can include numbers, lowercase letters, uppercase letters, and hyphens (-).
      It cannot start or end with a hyphen (-).
    Description: Conformance pack template bucket name
    Type: String

  pTemplatePrefix:
    Description: Path and file name of the conformance pack template e.g. /conformance-packs/my-conformance-pack.yaml
    Type: String


Conditions:
  cExcludedAccounts: !Not [!Equals [!Ref pExcludedAccounts, '']]

Resources:
  rConformancePack:
    Type: AWS::Config::OrganizationConformancePack
    Properties:
      DeliveryS3Bucket: !Ref pDeliveryBucketName
      DeliveryS3KeyPrefix: !Ref pDeliveryS3KeyPrefix
      ExcludedAccounts: !If [cExcludedAccounts, !Split [",", !Ref pExcludedAccounts], !Ref 'AWS::NoValue']
      OrganizationConformancePackName: !Ref pConformancePackName
      TemplateS3Uri: !Sub s3://${pTemplateBucketName}/${pTemplatePrefix}
