AWSTemplateFormatVersion: 2010-09-09
Description: >
  Enable Config aggregation.  This builds the base aggregator, and an aggregator authorization in each account,
  but the accounts need to be added to the aggregator via a Lambda function that will run periodically to ensure all
  accounts/regions are enabled.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Config Aggregator Attributes
        Parameters:
          - pAWSConfigAggregatorName
          - pAWSConfigManagementAccountId
          - pAggregatorRegion

    ParameterLabels:
      pAWSConfigManagementAccountId:
        default: AWS Config Aggregator Management Account ID
      pAWSConfigAggregatorName:
        default: AWS Config Aggregator Name
      pAggregatorRegion:
        default: AWS Config Aggregator Region

Parameters:

  pAWSConfigManagementAccountId:
    Type: String
    Description: >
      The AWS Config management account ID. For example, the security account ID

  pAWSConfigAggregatorName:
    Type: String
    Default: AWSConfigAggregator
    Description: >
      AWS Config Aggregator Name

  pAggregatorRegion:
    Type: String
    Default: us-east-1
    Description: >
      AWS region where AWS Config Aggregator will consolidate data

Conditions:
  cInSecurityAccount:
    !Equals
    - !Sub ${AWS::AccountId}
    - !Ref pAWSConfigManagementAccountId

Resources:
  rAggregatorAuth:
    Type: AWS::Config::AggregationAuthorization
    DeletionPolicy: Retain
    Properties:
      AuthorizedAccountId: !Ref pAWSConfigManagementAccountId
      AuthorizedAwsRegion: !Ref pAggregatorRegion

  rAggregator:
    Type: AWS::Config::ConfigurationAggregator
    Condition: cInSecurityAccount
    Properties:
      AccountAggregationSources:
        - AccountIds:
            - !Ref pAWSConfigManagementAccountId
          AllAwsRegions: true
      ConfigurationAggregatorName: !Ref pAWSConfigAggregatorName
