AWSTemplateFormatVersion: 2010-09-09
Description: >
  Enable Config aggregation.  This builds the base aggregator, and an aggregator authorization in
  each account, but the accounts need to be added to the aggregator via a Lambda function that will run periodically
  to ensure all accounts/regions are enabled.

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Config Aggregator Role Attributes
        Parameters:
          - pAWSConfigAggregatorRoleName
          - pPrimaryAccountId
          - pTagKey1
          - pTagValue1
          - pAWSConfigAggregatorLambdaRoleName

    ParameterLabels:
      pPrimaryAccountId:
        default: Organization Primary Account ID
      pAWSConfigAggregatorRoleName:
        default: AWS Config Aggregator Role Name
      pTagKey1:
        default: Lambda Role Tag Key
      pTagValue1:
        default: Lambda Role Tag Value
      pAWSConfigAggregatorLambdaRoleName:
        default: Lambda Role Name

Parameters:
  pPrimaryAccountId:
    Type: String
    Description: Organizations primary account ID

  pAWSConfigAggregatorRoleName:
    Type: String
    Description: AWS Config Aggregator Role Name
    Default: config-aggregator

  pAWSConfigAggregatorLambdaRoleName:
    Type: String
    Description: AWS Config Aggregator Lambda Role Name
    Default: config-aggregator-lambda

  pTagKey1:
    Type: String
    Description: Tag key

  pTagValue1:
    Type: String
    Description: Tag key value

Resources:
  rAWSConfigAggregatorRole:
    Type: "AWS::IAM::Role"
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W11
            reason: "Allow put and delete configuration aggregator for all aggregators"
          - id: W28
            reason: "Role Name required to restrict central account role"
    Properties:
      RoleName: !Ref pAWSConfigAggregatorRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS:
                - !Sub arn:${AWS::Partition}:iam::${pPrimaryAccountId}:root
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                aws:PrincipalArn: !Sub arn:${AWS::Partition}:iam::${pPrimaryAccountId}:role/${pAWSConfigAggregatorLambdaRoleName}
      Path: "/"
      Policies:
        - PolicyName: !Ref pAWSConfigAggregatorRoleName
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - config:DeleteConfigurationAggregator
                  - config:PutConfigurationAggregator
                Resource: !Sub arn:${AWS::Partition}:config:*:${AWS::AccountId}:config-aggregator/*
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1
