########################################################################
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
########################################################################
AWSTemplateFormatVersion: '2010-09-09'
Description: AWS Config Organization Aggregator

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: Config Aggregator Attributes
        Parameters:
          - pAggregatorName
      -
        Label:
          default: Config Aggregator Role Attributes
        Parameters:
          - pAggregatorRoleName
          - pTagKey1
          - pTagValue1
    ParameterLabels:
      pAggregatorName:
        default: Config Aggregator Name
      pAggregatorRoleName:
        default: Config Aggregator Role Name
      pTagKey1:
        default: Tag Key
      pTagValue1:
        default: Tag Value

Parameters:
  pAggregatorName:
    AllowedPattern: '^[\w\-]+'
    ConstraintDescription: Max 256 alphanumeric characters.
    Default: org-config-aggregator
    MaxLength: 256
    MinLength: 1
    Type: String

  pAggregatorRoleName:
    AllowedPattern: '^[\w+=,.@-]{1,64}$'
    ConstraintDescription: Max 64 alphanumeric characters. Also special characters supported [+, =, ., @, -]
    Default: org-config-aggregator
    Type: String

  pTagKey1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters and cannot be prefixed with "aws:".
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-''
    Description: Tag key
    Type: String

  pTagValue1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters.
      The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=', '+', '-'
    Description: Tag key value
    Type: String

Resources:
  rConfigAggregatorRole:
    Type: AWS::IAM::Role
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: The role name is defined to identify resources
    Properties:
      RoleName: !Ref pAggregatorRoleName
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: config.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSConfigRoleForOrganizations
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1

  rOrganizationConfigAggregator:
    Type: AWS::Config::ConfigurationAggregator
    Properties:
      ConfigurationAggregatorName: !Ref pAggregatorName
      OrganizationAggregationSource:
          AllAwsRegions: True
          RoleArn: !GetAtt rConfigAggregatorRole.Arn
