AWSTemplateFormatVersion: '2010-09-09'
Description: Creates the Macie KMS Key

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: KMS Key Attributes
        Parameters:
          - pLoggingAccountId
          - pMacieDeliveryKeyAlias
          - pOrgManagementAccountId
          - pTagKey1
          - pTagValue1

    ParameterLabels:
      pLoggingAccountId:
        default: Security Log Archive Account ID
      pMacieDeliveryKeyAlias:
        default: Macie Delivery KMS Key Alias
      pOrgManagementAccountId:
        default: Organization Management Account ID
      pTagKey1:
        default: Tag Key
      pTagValue1:
        default: Tag Value

Parameters:
  pLoggingAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Organization log archive account ID
    Type: String

  pMacieDeliveryKeyAlias:
    AllowedPattern: '^[a-zA-Z0-9/_-]+$'
    ConstraintDescription: >
      The alias must be string of 1-256 characters. It can contain only alphanumeric characters, forward slashes (/), underscores (_), and dashes (-).
    Default: MacieDeliveryKMSKey
    Description: Macie Delivery KMS Key Alias
    Type: String

  pOrgManagementAccountId:
    AllowedPattern: '^\d{12}$'
    ConstraintDescription: Must be 12 digits
    Description: Organization management account ID
    Type: String

  pTagKey1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters and cannot be prefixed with "aws:". The string can contain only the set of Unicode letters, digits,
      white-space, '_', '.', '/', '=', '+', '-''
    Description: Tag key
    Type: String

  pTagValue1:
    AllowedPattern: '^([\p{L}\p{Z}\p{N}_.:/=+\-@]*)$'
    ConstraintDescription:
      The string value can be Unicode characters. The string can contain only the set of Unicode letters, digits, white-space, '_', '.', '/', '=',
      '+', '-'
    Description: Tag key value
    Type: String

Resources:
  rMacieDeliveryKey:
    Type: AWS::KMS::Key
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: F76
            reason: Condition restricts principle to CloudFormation in the account
    Properties:
      Description: Macie Delivery Key
      EnableKeyRotation: True
      KeyPolicy:
        Id: !Sub ${pMacieDeliveryKeyAlias}
        Statement:
          - Action: 'kms:*'
            Effect: Allow
            Principal:
              AWS:
                - !Sub arn:aws:iam::${AWS::AccountId}:root
            Resource: '*'
            Sid: Enable IAM User Permissions

          - Action:
              - kms:Encrypt
              - kms:GenerateDataKey
            Effect: Allow
            Principal:
              Service: macie.amazonaws.com
            Resource: '*'
            Sid: Allow Macie to use the key

          - Action: kms:CreateAlias
            Condition:
              StringEquals:
                kms:CallerAccount: !Sub ${AWS::AccountId}
                kms:ViaService: !Sub cloudformation.${AWS::Region}.amazonaws.com
            Effect: Allow
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
            Resource: '*'
            Sid: Allow alias creation during setup

          - Sid: Allow log archive account access
            Effect: Allow
            Action:
              - kms:Decrypt
              - kms:DescribeKey
            Resource: '*'
            Principal:
              AWS:
                - !Sub arn:aws:iam::${pLoggingAccountId}:root
                - !Sub arn:aws:iam::${pOrgManagementAccountId}:root

          - Sid: Allow security account access
            Effect: Allow
            Action:
              - kms:DescribeKey
              - kms:Decrypt
            Resource: '*'
            Principal:
              AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
        Version: '2012-10-17'
      Tags:
        - Key: !Ref pTagKey1
          Value: !Ref pTagValue1

  rMacieDeliveryKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${pMacieDeliveryKeyAlias}
      TargetKeyId: !Ref rMacieDeliveryKey

Outputs:
  oMacieDeliveryKeyArn:
    Description: Macie Delivery KMS Key ARN
    Value: !GetAtt rMacieDeliveryKey.Arn
